name: Despliegue

on:
  push:
    branches: [main]

jobs:
  build:
    name: 🐘 Desplegar
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐝 Usar Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: 🦒 Instalar dependencias y hacer build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: 🦅 Enviar por FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.DOMINIO_070 }}
          username: ${{ secrets.USUARIO_070 }}
          server-dir: especiales/womansplaining/
          local-dir: ./docs/
          password: ${{ secrets.CLAVE_070 }}
